#!/bin/bash

echo -e "\033[1mSensors\033[0m"
if hash sensors 2>/dev/null; then
	sensors
else
	echo "sensors is not currently installed"
	echo
fi

echo -e "\033[1mDocker\033[0m"
if hash docker 2>/dev/null; then
	docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
else
	echo "docker is not currently installed"
	echo
fi

echo
echo -e "\033[1mNetwork\033[0m"
if hash ifstat 2>/dev/null; then
	INTERFACES=em1,docker0

	if [[ $(uname -s) == "Darwin" ]]; then
		INTERFACES=`route get 0.0.0.0 | grep interface | awk '{ print $2 }'`,lo0
	fi

	ifstat -i $INTERFACES -zntTS 0.1 1
else
	echo "ifstat is not currently installed"
fi
