#!/bin/sh

if hash boot2docker 2>/dev/null; then

	# get boot2docker status
	STATUS="$(boot2docker status)"

	# export environment variables are already set correctly
	if [ "$STATUS" = "running" ]; then
		export DOCKER_CERT_PATH=${HOME}/.boot2docker/certs/boot2docker-vm
		export DOCKER_TLS_VERIFY=1
		export DOCKER_HOST=tcp://$(boot2docker ip):2376
	fi

fi
