#!/bin/sh

# --foramt = ( across, commas, horizontal, long, single-column, verbose, vertical )
alias a="ls -A"
alias l="ls -AFhl"
alias cwd="basename `pwd`"

alias reload-profile="source ${HOME}/.zshrc"
alias remove-dsstore="find . -name '*.DS_Store' -type f -delete"

function hc() {
	local root name
	[ "$1" = "claude" ] && shift
	root=$(git rev-parse --show-toplevel 2>/dev/null) || root="$PWD"
	case "$root" in
		"$HOME/Developer/geld"/*) name="geld" ;;
		*) name=$(basename "$root") ;;
	esac
	ANTHROPIC_BASE_URL="http://127.0.0.1:8787/p/${name}" claude "$@"
}

bold=`tput bold`
attention=`tput setab 1`
normal=`tput sgr0`

function prev() {
	prev=`ls -d ../*/ | cut -f2 -d'/' | grep -B1 -E "(^|\s)${PWD##*/}($|\s)" | grep -v -E "(^|\s)${PWD##*/}($|\s)" | perl -pe 's/\r|\n//g'`

	if [ "${#prev}" -gt 0 ]; then
		cd ../$prev
	else
		echo "${bold}${attention}No more directories after this one '${PWD}'${normal}"
	fi
}

function next() {
	next=`ls -d ../*/ | cut -f2 -d'/' | grep -A1 -E "(^|\s)${PWD##*/}($|\s)" | grep -v -E "(^|\s)${PWD##*/}($|\s)" | perl -pe 's/\r|\n//g'`

	if [ "${#next}" -gt 0 ]; then
		cd ../$next
	else
		echo "${bold}${attention}No more directories after this one '${PWD}'${normal}"
	fi
}
