#!/bin/sh

if hash docker 2>/dev/null; then

	alias docker-rmi='docker rmi $(docker images -q --filter "dangling=true")'
	alias docker-rm='docker rm $(docker ps -q -f status=exited)'

	# Get latest container ID
	alias dl="docker ps -l -q"

	# Get container process
	alias dps="docker ps"

	# Get process included stop container
	alias dpa="docker ps -a"

	# Get images
	alias di="docker images"

	# Get container IP
	alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

	# Run deamonized container, e.g., $dkd base /bin/echo hello
	alias dkd="docker run -d -P"

	# Execute a command on an existing container, e.g., $dke container-name /bin/bash
	alias dke="docker exec -i -t"

	# Run interactive container, e.g., $dki base /bin/bash
	alias dki="docker run -i -t -P"

	# Stop all containers
	alias dstop='docker stop $(docker ps -a -q);'

	# Remove all exited containers
	alias drm='docker rm'

	# Remove all exited containers
	alias drme='docker rm $(docker ps -q -f status=exited)'

	# Remove all containers
	alias drma='docker rm $(docker ps -a -q)'

	# Stop and Remove all containers
	alias drmf='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'

	# Remove all images
	alias dri='docker rmi $(docker images -q)'

	# Trim all dangling images
	alias dti='docker rmi $(docker images -q --filter "dangling=true")'

	# Dockerfile build, e.g., $dbu repo/test
	dbu() { docker build -t=$1 .; }

	# Show all aliases related docker
	dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

fi
