#!/bin/sh

if hash git 2>/dev/null; then
	alias galias='echo "\nGit config aliases:\n" && git config --get-regexp alias && echo "\n\nShell aliases:\n" && alias | grep git'
	alias grom="git rebase origin/master"
fi
