#!/bin/zsh

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]} r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 3 numeric
zstyle ':completion:*' prompt '%e errors found'
zstyle ':completion:*' substitute 1
zstyle :compinstall filename "${HOME}/.shell-config/config/compinstall"

autoload -Uz compinit
compinit
# End of lines added by compinstall
