#!/bin/sh

if hash boot2docker 2>/dev/null; then

	STATUS="$(boot2docker status)"

	if [ "$STATUS" = "running" ]; then
		export DOCKER_HOST=tcp://$(boot2docker ip):2376
		export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
		export DOCKER_TLS_VERIFY=1
	fi

fi
